import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	apiReferenceSidebar: [
		{
			// Autogenerate sidebar from the root of the API docs path
			// (i.e., from packages/ts-lib/docs-markdown)
			type: "autogenerated",
			dirName: ".", 
		},
	],
};

export default sidebars;
